apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-replica-config
  namespace: database
data:
  postgresql.conf: |
    listen_addresses = '*'
    hot_standby = on
  setup-replica.sh: |
    #!/bin/bash
    until pg_isready -h postgresql-primary.database.svc.cluster.local -U postgres; do
      echo "Waiting for primary to be ready..."
      sleep 2
    done
    pg_basebackup -h postgresql-primary.database.svc.cluster.local -U replicator -D /var/lib/postgresql/data/pgdata -Fp -Xs -P -R
    chown -R postgres:postgres /var/lib/postgresql/data/pgdata
